// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8kU_xNNWAvqgxrzW3cl35tEqJbw37syA',
    appId: '1:463189541422:web:101315ce044b0accca15bf',
    messagingSenderId: '463189541422',
    projectId: 'smart-quiz-63065',
    authDomain: 'smart-quiz-63065.firebaseapp.com',
    storageBucket: 'smart-quiz-63065.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWjt82DGKBpP19ECck18f-Xo4Jg4HTm9c',
    appId: '1:463189541422:android:5d70f79c56c81aa3ca15bf',
    messagingSenderId: '463189541422',
    projectId: 'smart-quiz-63065',
    storageBucket: 'smart-quiz-63065.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmCwknIwjr30oEFKkrSkkyhArmWRyaclQ',
    appId: '1:463189541422:ios:87573fad6079c6f0ca15bf',
    messagingSenderId: '463189541422',
    projectId: 'smart-quiz-63065',
    storageBucket: 'smart-quiz-63065.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmCwknIwjr30oEFKkrSkkyhArmWRyaclQ',
    appId: '1:463189541422:ios:87573fad6079c6f0ca15bf',
    messagingSenderId: '463189541422',
    projectId: 'smart-quiz-63065',
    storageBucket: 'smart-quiz-63065.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );
}
